### ISSUE TITLE
your normalization has a problem

### ISSUE THREAD

**Issue by iBizzard** [fiy2W/mri_seq2seq#4]
Your norm has a strange operation: "*2". Why are you multiplying by 2? Aren't you normalizing to [-1, 1]? I don't understand. Can you explain this?
def norm(self, arr):
    """ norm (0, 99%) to (0, 1)
    arr: [s,d,w,h]
    """
    amax = np.percentile(arr, 99) * 2
    arr = np.clip(arr, 0, amax) / amax * 2 - 1
    return arr

**Comment by fiy2W** [comment]
Sorry for confusing you. There are some problems with the code comments.
In this function, we use `np.percentile(arr, 99) * 2` as the maximum intensity and then normalize it to (-1, 1).
This is because, through this normalization, the visualization effect of the brats dataset is better. T1 and T1Gd will have similar intensities ​​in the white matter area, making the tumor area more clearly contrasted. `99%*2` is an empirical value and can be adjusted according to the actual situation of the dataset.

**Comment by iBizzard** [comment]
Thank you for your explanation, I understand now. I sincerely apologize for any unnecessary trouble I caused you.

> Sorry for confusing you. There are some problems with the code comments. In this function, we use `np.percentile(arr, 99) * 2` as the maximum intensity and then normalize it to (-1, 1). This is because, through this normalization, the visualization effect of the brats dataset is better. T1 and T1Gd will have similar intensities ​​in the white matter area, making the tumor area more clearly contrasted. `99%*2` is an empirical value and can be adjusted according to the actual situation of the dataset.
